### ISSUE TITLE
Tests needed for any top level recipe

### ISSUE THREAD

**Issue by vsoch** [buildtesters/schemas#1]
- read in the associated schema from file, assert that all required fields are there, and of correct types. This should not be hard coded in the code for buildtest, but mostly in the schema file here (that buildtest knows how to use)
 - the recipe type must be one that is known / registered to buildtest, meaning there is a class name in buildtest/tools/buildsystem/base.py (not written yet)
 - Every key in a test file must be unique
 - Metadata parsing should be shared (e.g., all recipes can have maintainer and description, and are required to have a type).

**Comment by vsoch** [comment]
This is also all set! The `global/outer.schema.json` suits this purpose, and I've already been using it in early testing for buildtest test configs. I'm going to leave it open because I haven't tested what happens if we have non unique keys, and I want to make sure this won't lead to weird errors.

**Comment by shahzebsiddiqui** [comment]
@vsoch i believe this issue could be closed. The file ``test_global.py`` is where we can test the global schema and the valid/invalid examples are where we should put the examples.
